### ISSUE TITLE
Connection to RoboController fails

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/serial_bridge#7]
The connection to RoboController board fails and the node crashes 

Running procedure:
http://wiki.officinerobotiche.it/index.php/Category:ROS#First_Test

Output:
[ INFO] [1419419069.793259040]: Open Serial /dev/ttyUSB0:115200
[ INFO] [1419419069.795412807]: Standard Controller
[ERROR] [1419419070.801983429]: Timeout sync packet n: 0

**Comment by katodo** [comment]
Problem was https://github.com/officinerobotiche/uNAV.X/issues/24 related, it was solved with this commit https://github.com/officinerobotiche/uNAV.X/commit/5aa14abec61babafce87590dce257978943fa86b
